### ISSUE TITLE
Hardcoded assets in app

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-sample-app-react#109]
### Motivation

Currently, it's unclear at first what content is hardcoded in the app and what is drawn from Kentico Cloud. For example, the Hero unit on the homepage is not drawn from Kentico Cloud. So it's possible to run the app and get confused when changing the Hero unit in Kentico Cloud doesn't change the content in the app.

### Proposed solution

- create an account in [Kentico Cloud](https://app.kenticocloud.com/sign-up) and let it generate a sample project for you
- search for `jpg` in this repo 
  - [2 occurrences](https://github.com/Kentico/cloud-sample-app-react/search?q=jpg&unscoped_q=jpg)
- replace all hardcoded assets with ones from Kentico Cloud. 
-- use the [JavaScript SDK](https://github.com/Enngage/kentico-cloud-js/tree/master/packages/delivery) to retrieve the assets using their codenames
-- see the [docs](https://developer.kenticocloud.com/docs/javascript) for more details about how to work with Kentico Cloud API
- remove replaced assets from this repository

### Additional context

- [Example of confusion](https://app.intercom.io/a/apps/e42kus8l/inbox/inbox/conversation/18938021497).
- the same issue is in the [vue sample app](https://github.com/Kentico/cloud-sample-app-vue/issues/17)

**Comment by petrsvihlik** [comment]
@agoiabel  thanks for your interest. I have updated the readme. Let me know if you still have some questions. I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

**Comment by saravanan10393** [comment]
@agoiabel is this issue taken. If not i can help with it.

**Comment by agoiabel** [comment]
Yes please, you can help with it, I really don't fully understand the task.

**Comment by petrsvihlik** [comment]
@saravanan10393 the issue is free. i'll assign it to you if you accept the invite i sent you. :)

**Comment by diegoalmesp** [comment]
Hello! is this taken? Seems like a great fit for my first open source contrib :)

**Comment by petrsvihlik** [comment]
Hi @diegoalmesp , I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.

**Comment by sureife** [comment]
Hi @petrsvihlik . Is anyone working on this, can I contribute?

**Comment by Simply007** [comment]
Hey @sureife,

this issue is currently being fixed in #129.

There is a similar issue on the Vue sample application:
* https://github.com/Kentico/cloud-sample-app-vue/issues/17

I've just sent you an invitation to the Kentico GitHub Organization. If you accept it, I'll be able to assign the issue to you in case you want it.

**Comment by Simply007** [comment]
Fixed in #129
