### ISSUE TITLE
Handle missing values in Preview for Metadata component

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-react#126]
### Motivation

As was described in #115, there is insufficient check for missing values for `Metadata` component values.

Great jop @Karl-EdwardFPJeanMehu, thanks!
### Proposed solution

According to the metadata (i.e. ogImage) I would recommend using the lodash for the value check:
```
import _ from 'lodash';
...
      {!_.has(props, 'ogImage.value[0].url') ? null : (  // current state =>  {!props.ogImage ? null : (
        <meta property=\"og:image\" content={props.ogImage.value[0].url} />
      )}
```

**Comment by Karl-EdwardFPJeanMehu** [comment]
I'm interested.

**Comment by petrsvihlik** [comment]
Hi @Karl-EdwardFPJeanMehu , I've just sent you an invitation to the project. I'll be able to assign the issue to you once you accept it.
