### ISSUE TITLE
Replace hardcoded sample project items count in SelectedProject.js

### ISSUE THREAD

**Issue by makma** [Kentico/cloud-sample-app-react#133]
### Motivation

In */src/Utilities/SelectedProject.js* there is a hardcoded SAMPLE_PROJECT_ITEM_COUNT constant which is used in the wizard. 

This wizard checks if the Delivery API has already accessible all items in the user's Dancing Goat project and if the project is fully accessible. If the count of all items in the project is more or equals to items from constant then we consider the project to be ready.

However, if the user's sample Dancing Goat project changes (we add/remove new content) this logic might not work.  Under the hood, we clone the Dancing Goat project from 'one-source-of-truth' project.

### Proposed solution

The goal of this issue is to implement logic which will get a count of items in from this source (-of-truth) project (projectId: 975bf280-fd91-488c-994c-2f04416e5ee3) and store it to an existing (non)constant which will be checked the same way as it is right now.

Note: It might be a good idea to adjust if condition in *Configuration.js*, too.
Something like ... if (response.items.length > SAMPLE_PROJECT_ITEM_COUNT) in *waitUntilProjectAccessible* function.

**Comment by sheidaee** [comment]
Hello,
I would work on this issue.

**Comment by makma** [comment]
Hi @sheidaee, thank you for your interest! I've sent you an invitation to the organization. Once you accept it, I can assign you this issue. Welcome to  Kentico Open Source Community!

**Comment by Simply007** [comment]
@sheidaee - just sending a related issue https://github.com/Kentico/cloud-sample-app-vue/issues/26 
* there is a hint how it was solved in VueJs by @liamgold.
