### ISSUE TITLE
Extract API keys definition to .env

### ISSUE THREAD

**Issue by liamgold** [Kentico/cloud-sample-app-react#134]
### Motivation

@Simply007 originally logged an issue against the Vue sample project, which would probably be a good idea for the react sample project too.

See https://github.com/Kentico/cloud-sample-app-vue/issues/23#issue-382187178 for detailed information.

The general idea is to move the recommended configuration of sensitive key information from the `Client.js` file into git ignored `.env.*` files. 

### Proposed solution

Best practice nowadays is to use environment variables stored in .env file.

* Set up .gitignore to ignore .env file
* Configure `Client.js` to use .env definition for keys (projectId and previewApiKey)
* Update Readme

### Additional context

* Highly used is dotenv library: https://www.npmjs.com/package/dotenv
* Or investigate react environment variables: https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables

**Comment by Simply007** [comment]
Being implemented in #136

**Comment by Simply007** [comment]
Fixed in #136
