### ISSUE TITLE
Fix Glitch setup

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-react#135]
### Brief bug description

[Remix on Glitch button](https://github.com/Kentico/cloud-sample-app-react#get-creative) does not work. 

It was introduced in https://github.com/Kentico/cloud-sample-app-react/commit/8b9823751f69e0d334608f41cdd204537eec244a

Current section 

### Repro steps

1. Go to https://github.com/Kentico/cloud-sample-app-react#get-creative
1. Click on Remix on Glitch button
1. See error

### Expected behavior

The button should work or should be removed.

**Comment by blakewenloe** [comment]
I have been playing with this for a bit. It imports successfully when i'm logged in, but throws an error when i'm logged out.

```
"/opt/watcher/scripts/github-import.sh: line 78: header_arg[@]: unbound variable

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat '/tmp/tmp.kweQN5WyOd/*': No such file or directory
"
```

I'm assuming you have to be logged in for the app to create/write to a `/tmp/` directory?

**Comment by blakewenloe** [comment]
Similar issue reported here: https://support.glitch.com/t/github-imports-silently-fail-when-not-logged-in/1013

**Comment by blakewenloe** [comment]
Fixed with https://github.com/Kentico/cloud-sample-app-react/pull/139
