### ISSUE TITLE
Update integration sample - Hubspot

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-react#147]
### Brief bug description

After the [rebranding from Kentico Cloud to Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent) there are still some samples that use old naming in branches named `samples/*`.

Until the end of October endpoint on domain `kenticocloud.com` stop working and there will be redirect performed:
* https://docs.kontent.ai/reference/api-changelog#a-api-urls-changed

#### Transfer changes made in https://github.com/Kentico/kontent-sample-app-react/pull/140 to the [**`samples/hubspot`**](https://github.com/Kentico/kontent-sample-app-react/tree/samples/hubspot) branch

* Update dependency from `kentico-cloud-delivery` to `@kentico/kontent-delivery`
    * adjust the breaking changes
* Update dependency `@chevtek/react-spinners` to `@simply007org/react-spinners`
   * no breaking changes
* Rename Kentico Cloud to Kentico Kontent
* adjust `travis.yml` to use the correct domain for deployment

**Comment by kaiquesilva27** [comment]
HI! @Simply007 Can I take up this issue? 😄

**Comment by Simply007** [comment]
It'S yours @kaiquesilva27!

take a look at a similar issue: https://github.com/Kentico/kontent-sample-app-react/pull/151 comments.

**Comment by Simply007** [comment]
Feel free to [join Kentico organization](https://kentico.github.io/). If you do so, you'll be able to interact with other Kentico GitHub community members in out [Global collaborators dicsussions](https://github.com/orgs/Kentico/teams/global-collaborators) as well as getting the fresh info about Kentico Github activity.
