### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-sample-app-react#18]
Similarly to https://github.com/Kentico/cloud-sample-app-net/pull/19, add a Spanish translation of the site.

- [x] Add a language switch
- [x] Add appropriate routing mechanism using router-react, or router-react-redux (or a similar standardized technology)
- [x] Add a globalization (resource) strings support (again, choose a common approach)
- [x] Translate globalization strings
- [x] Translate texts in the KC Sample Project (separate issue: #20)

**Comment by beemtz** [comment]
Hi! I'd love to help with this :) Spanish is my first language and I translated if-me.org... msg me!

**Comment by petrsvihlik** [comment]
Hi @beemtz,
Thanks for your interest!

Not too long ago, we added [localization support](https://kenticocloud.com/blog/working-with-localization-in-kentico-cloud) to our headless CMS - Kentico Cloud. 

We demonstrated the functionality in the [sample app for .NET](https://github.com/Kentico/cloud-sample-app-net) and we'd like to do the same for this sample react app.

So the idea here is to add a language dropdown to the web site which would switch the context between English and Spanish culture. Behind the scenes, it will basically be adding of a language parameter to the calls made by the delivery client. This is well described here: https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#getting-localized-items

Texts that are not being retrieved from the Kentico Delivery API (=are hardcoded...eg. buttons) should be translated as well. We should use a standardized approach to do this...e.g. https://stackoverflow.com/questions/14358817/best-practice-for-localization-and-globalization-of-strings-and-labels

There is a bonus part as well: some of the texts that come from the Kentico Delivery API (probably most of them) are not translated to Spanish. It'd be great to have someone who speaks Spanish translate them. :) Let me know if you're interested in helping out here as well.

Localization-related changes in the .NET app (for inspiration):
- https://github.com/Kentico/cloud-sample-app-net/pull/19
- https://github.com/Kentico/cloud-sample-app-net/pull/20
- https://github.com/Kentico/cloud-sample-app-net/pull/21
- https://github.com/Kentico/cloud-sample-app-net/pull/25
- https://github.com/Kentico/cloud-sample-app-net/pull/26
- https://github.com/Kentico/cloud-sample-app-net/pull/38

**Comment by beemtz** [comment]
Hello!

I’m mostly interested in the translation part per se. I’m still too scared of messing with repos on my own. :S

B*

**Comment by petrsvihlik** [comment]
hey @beemtz , sorry for the delay. i needed to discuss the approach with my colleagues. i've created a separate issue for the translations themselves. feel free to accept the invitation to this project and assign the issue (#20) to yourself.

**Comment by petrsvihlik** [comment]
@JanLenoch could you please give @beemtz some guidance? thx

**Comment by Simply007** [comment]
Started with upgrading react router to v4
https://github.com/Kentico/cloud-sample-app-react/tree/multilingual-support

**Comment by Simply007** [comment]
Submitted a pull request with, let's say extendable support of multiple language with Spanish translation
https://github.com/Kentico/cloud-sample-app-react/pull/64
