### ISSUE TITLE
Add a showcase of the content type snippets

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/cloud-sample-app-react#55]
Kentico Cloud now supports so called [content type snippets](https://help.kenticocloud.com/define-content-structure/structure/using-content-type-snippets). These are sets of content elements that can be added to multiple content types to enrich their structure but still be managed from a single place.

The Delivery API responses contain both the elements originating from snippets alongside their own elements. The only difference is that snippets have code names prefixed with the code name of the respective snippet. The format of code names is `[code name of snippet]__[code name of element]`.

A shortened example of a content item:

    {
        "item": {
            "system": {
                // ...
                "type": "brewer",
		// ...
            },
            "elements": {
		// ...
                "product_name": {
                    "type": "text",
                    "name": "Product name",
                    "value": "AeroPress"
                },
		// ...
                "metadata__meta_title": {
                    "type": "text",
                    "name": "Meta title",
                    "value": null
                },
		// ...
            }
        },
        "modular_content": {}
    }

The goal of this task is to implement support for rendering content items of content types that utilize a content snippet. For that scenario, we've prepared a sample content snippet that enriches other content types with SEO-related data, such as [og:title, og:description](https://github.com/Kentico/cloud-sample-app-net/pull/44/files#diff-2251ad254d82c4cb5cde25af83c1c57a), etc. which are then rendered in the [`<head>`](https://github.com/Kentico/cloud-sample-app-net/pull/44/files#diff-90b33e16556b5f65bc52a24e8e53c23b) of the page.

**Suggested approach:**
- [ ] use the [model generator](https://github.com/Enngage/kentico-cloud-js/tree/master/packages/model-generator) to regenerate the [models](https://github.com/Kentico/cloud-sample-app-react/tree/master/src/Models) (in order for them to have the desired og-related properties)
- [ ] adjust the code of the sample application so that it renders the SEO metadata in the `<head>` of the page

**Comment by JanLenoch** [comment]
The "Article" content type no longer needs the "Meta keywords" and "Meta description" elements.

![article meta keywords description deprecated](https://user-images.githubusercontent.com/17413329/33882418-575877e6-df38-11e7-9949-85a33da5f94e.png)

Remove the two corresponding properties of the Article model class.

**Comment by Simply007** [comment]
Article fields removed from models in:
https://github.com/Kentico/cloud-sample-app-react/pull/7

**Comment by liamgold** [comment]
I've given this a go, used react-helmet for the handling of adding/removing and inheriting the metadata.

While testing I also noticed an issue with the brewer links were broken - so fixed those too.  Will do a PR now.

**Comment by petrsvihlik** [comment]
implemented in #94
