### ISSUE TITLE
Make a footer part of the site as a react element

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-react#65]
Currently footer is hardcoded in the html markup, so that it is not possible to localize its content.

We want to transform this part of the site to a react rendered part. Defined it as a component and use prepared infrastructure to translate its content.

![image](https://user-images.githubusercontent.com/9218736/34835751-0f836b9e-f6f6-11e7-892b-754820c319f6.png)

**Comment by sandiri-s** [comment]
Hi, I would like to contribute to this issue. I have worked on the few samples react applications in the past and this will be my first open source contribution if accepted. 

Thanks.

**Comment by Simply007** [comment]
Hi,

that's great to hear @sandiri-s. I think this task is perfect as a first contribution. 
Please go through the [Code of conduct](https://github.com/Kentico/Home/blob/master/CODE_OF_CONDUCT.md) and [Contributing](https://github.com/Kentico/Home/blob/master/CONTRIBUTING.md) guidelines to get familiar with our contribution process.

If you have any question, or you need to specify the issue requirement, feel free to ask here.

Looking forward for the pull request
Ondřej

**Comment by petrsvihlik** [comment]
Hi @sandiri-s , if you accept the collaborator invite I've just sent you, we'll be able to assign the issue directly to you.

**Comment by prakharcipher** [comment]
I'd like to contribute to this issue and fix it right away. Please let me know.

**Comment by petrsvihlik** [comment]
folks, whoever submits the PR first, wins :D so go for it!

**Comment by jmb521** [comment]
Is this still open?

**Comment by petrsvihlik** [comment]
there's a PR open for this - #67

**Comment by Simply007** [comment]
@jmb521 it is nearly the month, since the last action was made in the pull request.

 So if you are interested create your own pull request, let!s do it.

Take a look to the pull request comments:
https://github.com/Kentico/cloud-sample-app-react/pull/67

The work consist from:
- move html from index.html to the component (do not forget to change class attributes to className)
- change display type of the footer element in css (desribed in pullrequest comment)
- (optionally) set up the translation for the element as is in other components

If you have any question, feel free to ask :-)

**Comment by Simply007** [comment]
Implemented in https://github.com/Kentico/cloud-sample-app-react/pull/70
