### ISSUE TITLE
Language specific URL slugs

### ISSUE THREAD

**Issue by MartinaFKentico** [Kentico/cloud-sample-app-react#73]
We have a new feature, language-specific URL slugs generated from Text elements. Consider if the React sample app needs to be updated.

See the task in JIRA: https://kentico.atlassian.net/browse/DEL-1635

**Comment by ivanaliptakova** [comment]
**Content types with changed url slug configuration: changed items**
About us: 1 EN (changed to custom, value not changed), 1 ES (changed to custom, value changed)
Accessory: not changed
Article: EN not changed, ,ES items changed
Brewer: not changed items
Coffee: not changed items
Grinder: not changed items
Home: ES home changed to casa (custom mode)

**Comment by petrsvihlik** [comment]
@Simply007 could you please either sync with with @ivanaliptakova to find out what's the preferred behavior or call a meeting for the three of us?

**Comment by Simply007** [comment]
I have consulted this with @oravecjakub and correct configuration is already on development environment, so it was my fault - i have checked live project.

**Comment by Simply007** [comment]
Final decision - agreed with @oravecjakub:
About us:
- en /en-us/about-us
- es  /es-es/acerca-de
Home:
- en /en-us/ /en-us/home
- es /es-es/ /es-es/inicio

Articles: 
- en /en-us/articles/articleId -> Redirect -> en-us/articles/enArticleUrlSlug (two requests required - one for resolving urlSlug second for return value)
- es /es-es/articulos/articleId -> Redirect ->  /es-es/articulo/esArticleUrlSlug (two requests required - one for resolving urlSlug second for return value)

No other changes

**Comment by Simply007** [comment]
We dont need to change home, because it is registered under "/" route.

About us is implemented
Articles are not performing redirect, because it is no necessary.

We will have /en-us/articles/articleId (/es-es/articles/articleId) route and the request for ID with language specification return correct language data.

https://github.com/Kentico/cloud-sample-app-react/pull/74

**Comment by Simply007** [comment]
Added another pull request:
https://github.com/Kentico/cloud-sample-app-react/pull/76
