### ISSUE TITLE
Add ESLint & unify coding style

### ISSUE THREAD

**Issue by Enngage** [Kentico/cloud-sample-app-react#84]
There are some inconsistencies in code style, especially in the use of apostrophes vs double quotes.

Example:

```
import { resolveContentLink } from '../Utilities/ContentLinks'
import BrewerStore from "../Stores/Brewer";
```

Suggested approach:
- [ ] fix the ESLint configuration in this [project](https://github.com/Kentico/cloud-sample-app-react/blob/master/package.json)
  - there are some [standard configs](https://github.com/standard/eslint-config-standard-react) available on the web
  - ideally, configure ESLint to fix issues automatically
- [ ] use ESLint to identify issues and fix them

**Comment by cbeard87** [comment]
Since I recently set this up on the Vue sample app, making a similar config for React would be pretty quick and simple. If you’d like me to take this one as well, I’d be more than happy to work on it.

**Comment by petrsvihlik** [comment]
Absolutely :) It'd be great if you could pick this one up as well, @cbeard87!
