### ISSUE TITLE
Remove deprecated livecycle method - UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by Simply007** [Kentico/cloud-sample-app-react#97]
### Motivation

In React v17 `UNSAFE_componentWillReceiveProps` method is deprecated and should be replaced by another lifecycle method.

### Proposed solution

Change calling of `UNSAFE_componentWillReceiveProps` method to some more appropriate - some tips point to https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops.
Try that one and make a testing of all occurrences.

### Additional context

* Documentation: https://reactjs.org/docs/react-component.html#updating
* Commit link, that introduced new React: https://github.com/Kentico/cloud-sample-app-react/pull/93/files

**Comment by vipulbhj** [comment]
Is this still open. Can I try this ?

**Comment by vipulbhj** [comment]
My Stack Node and react. I also have worked with flask. Yes I would like to try something else. If you have anything for me.

**Comment by Simply007** [comment]
Hi @vipulbhj,

I have tried to find an issue for you. 
We have a javascript mono repository containing a generator of javascript/typescript [DTO ](https://en.wikipedia.org/wiki/Data_transfer_object) models. It would be great to cover this package by tests.

Here is more information: 
* https://github.com/Enngage/kentico-cloud-js/issues/66

Hope you will like it!
